### ISSUE TITLE
Performance issue for queries

### ISSUE THREAD

**Issue by Bktero** [ravendb/RavenDB-Python-Client#116]
Hello

I am new to RavenDB (and NoSQL DBs in general).

I have a simple database, hosted on a free instance of RavenDB cloud. I have a collection named 'Pressures' of 5145 documents. Each document is very lightweight. For instance, here is one of these documents:

```json
{
    "timestamp": "2021-12-31T12:01:25.5100400",
    "pressure": 6.46,
    "@metadata": {
        "@collection": "Pressures",
        "Raven-Python-Type": "RavenDataTypes.Pressure"
    }
}
```

In RavenDB studio, I go to **Documents** / **Query** and execute the simplest query to get all the documents in this collection: `from Pressures`. The query succeeds in a few milliseconds and the documents are displayed almost immediately.

When I try to make the same request in Python, it takes about 2 seconds. Here is my code to reproduce the issue:

```python
from timeit import default_timer as timer

import RavenStore  # hides the creation of a DocumentStore instance

with RavenStore.open_session() as session:
    for i in range(0, 10):
        start = timer()
        results, stats = session.query(collection_name='pressures', with_statistics=True)
        documents = list(results)
        stop = timer()
        print('{} documents retrieved in {} seconds (query = {} ms)'.format(len(documents), (stop - start), stats['DurationInMs']))
````

It outputs:

```
5145 documents retrieved in 2.5156666000000003 seconds (query = 13 ms)
5145 documents retrieved in 1.7201680000000006 seconds (query = 3 ms)
5145 documents retrieved in 1.6280774999999998 seconds (query = 3 ms)
5145 documents retrieved in 1.7873899 seconds (query = 3 ms)
5145 documents retrieved in 1.7396721999999993 seconds (query = 5 ms)
5145 documents retrieved in 1.746634499999999 seconds (query = 6 ms)
5145 documents retrieved in 1.7962476999999986 seconds (query = 3 ms)
5145 documents retrieved in 1.7754951000000005 seconds (query = 2 ms)
5145 documents retrieved in 1.9398379999999982 seconds (query = 7 ms)
5145 documents retrieved in 2.3221901000000003 seconds (query = 3 ms)
```

It seems that almost all the time is consumed on this line: `documents = list(results)`.

Why is the query super fast to display the documents in RavenDB's studio, while Python is super slow to get them (and not even displaying them)?

**Comment by ayende** [comment]
You aren't measuring the same thing, I'm afraid. 

The `stats` gives you the query duration on the server side. The time that _you_ measure includes:

* Sending 5,145 documents from the server to the client
**This includes the network time**
* Deserializing 5,145 documents from JSON to Python objects

Can you run this with `cProfile` ? 

https://www.machinelearningplus.com/python/cprofile-how-to-profile-your-python-code

If you are running on the cloud, remember that the server (free ones) is located in the states, so you're showing high latency in that regard.

**Comment by Bktero** [comment]
I understood that the query itself is quite fast and this is why `stats` gives a very duration. The same applies to the query in the studio. This is why I am talking about displaying the data in the studio, which _seems_ to be almost instantaneous.

As you said, most of the time is actually spent downloading the data and recreating Python objects. This is done with `documents = list(results)`. Other tests (not visible in my snippet above) have shown that manipulating data once they have been downloaded is very fast.

Here is a new code that uses `cProfile` :

```python
from timeit import default_timer as timer
import cProfile

import RavenStore  # hides the creation of a DocumentStore instance


def run_query(session):
    results = session.query(collection_name='pressures')
    documents = list(results)
    return documents


def format_data(session, documents):
    pressures = list()
    for document in documents:
        document_id = session.advanced.get_document_id(document)
        pressures.append({'uid': document_id} | document.to_dict())
    return pressures


def query_all_pressures():
    with RavenStore.open_session() as session:
        documents = run_query(session)
        format_data(session, documents)


cProfile.run("query_all_pressures()", sort='cumtime')
```

The `format_data()` is here only to see how fast it is to manipulate the data.

Here is the beginning of the script's output:

```
         1228377 function calls (1145982 primitive calls) in 1.926 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     21/1    0.001    0.000    1.928    1.928 {built-in method builtins.exec}
        1    0.000    0.000    1.928    1.928 testing.py:21(query_all_pressures)
        1    0.000    0.000    1.841    1.841 testing.py:7(run_query)
        1    0.000    0.000    1.840    1.840 session_query.py:100(__iter__)
        1    0.014    0.014    1.840    1.840 session_query.py:778(_execute_query)
        1    0.000    0.000    1.422    1.422 requests_executor.py:105(execute)
        1    0.000    0.000    1.020    1.020 requests_executor.py:135(execute_with_node)
        1    0.000    0.000    1.005    1.005 sessions.py:470(request)
        1    0.000    0.000    1.003    1.003 sessions.py:626(send)
      356    0.001    0.000    0.752    0.002 socket.py:690(readinto)
      356    0.001    0.000    0.750    0.002 ssl.py:1230(recv_into)
      356    0.001    0.000    0.749    0.002 ssl.py:1090(read)
      356    0.748    0.002    0.748    0.002 {method 'read' of '_ssl._SSLSocket' objects}
        3    0.000    0.000    0.656    0.219 models.py:823(content)
       14    0.001    0.000    0.656    0.047 {method 'join' of 'bytes' objects}
      145    0.000    0.000    0.655    0.005 models.py:754(generate)
      145    0.000    0.000    0.655    0.005 response.py:554(stream)
      145    0.000    0.000    0.655    0.005 response.py:724(read_chunked)
      144    0.000    0.000    0.652    0.005 response.py:702(_handle_chunk)
      161    0.000    0.000    0.652    0.004 client.py:605(_safe_read)
      163    0.002    0.000    0.652    0.004 {method 'read' of '_io.BufferedReader' objects}
       28    0.403    0.014    0.403    0.014 {method 'acquire' of '_thread.lock' objects}
        1    0.000    0.000    0.402    0.402 requests_helpers.py:14(join)
        1    0.000    0.000    0.402    0.402 threading.py:1001(join)
        2    0.000    0.000    0.402    0.201 threading.py:1039(_wait_for_tstate_lock)
     5145    0.026    0.000    0.368    0.000 utils.py:100(convert_to_entity)
```

And much later we can see:

```
        1    0.005    0.005    0.086    0.086 testing.py:13(format_data)
```

> If you are running on the cloud, remember that the server (free ones) is located in the states, so you're showing high latency in that regard.

And I'm in France, that's so not quite close...

**Comment by ayende** [comment]
Yes, this is the key factor:

`1.005 sessions.py:470(request)`

That is almost the entire time taken, which is spent over the network.

**Comment by Bktero** [comment]
I will try the same tests with a local instance of RavenDB to see the effect of network.

I have tried to use NodeJS with my current RavenDB cloud instance::

```javascript
const session = store.openSession();

const start = new Date()
const query = session.query({ collection: 'pressures' }).take(200);
const all = await query.all();
const stop = new Date()
console.log(all.length, 'documents loaded in', (stop - start), 'ms');
```

Durations are also important. On Friday, it was more around 1.5 to 2 seconds. This morning, it takes around 3 seconds...

**Comment by ayende** [comment]
Locally, there should be very little latency. Also please note that you are testing against a (very) remote instance that is running on the free tier.

**Comment by Bktero** [comment]
I have downloaded RavenDB and run the server locally (most basic setup: no licence, no certificate). I have run my first script again and it is much faster. Each query takes between 250 and 600 ms for 6180 documents.

The duration seems to vary from one execution (of the script) to the other, sometimes a lot, but it's OK for me.

Thanks for you help! I close the issue.

**Comment by ayende** [comment]
Just to note, there is a pretty high cost for the _initial_ connection. try running a loop inside the same script.
Also, getting 1000s is always going to be costly, you are usually meant to either stream them or use pages
