### ISSUE TITLE
Random ordering does not work as it is getting escaped

### ISSUE THREAD

**Issue by danielwinkler** [ravendb/RavenDB-Python-Client#132]
In pyravendb:

When creating a query that does random ordering, the `random()` part of `ORDER BY random()` is getting escaped by the `escape_if_needed` method.
The result `ORDER BY 'random()'` has no effect.

**Comment by ml054** [comment]
Hi @danielwinkler 

Which version are you using?

**Comment by danielwinkler** [comment]
Hi @ml054 

The latest release 5.0.0.2
https://github.com/ravendb/ravendb-python-client/blob/dbe51ee8eea166e0d9e60897ab480dd9a693366b/pyravendb/store/session_query.py#L665

**Comment by danielwinkler** [comment]
A quick fix was to  allow for `(` and `)` in 
https://github.com/ravendb/ravendb-python-client/blob/dbe51ee8eea166e0d9e60897ab480dd9a693366b/pyravendb/store/session_query.py#L330
but i have no idea about other implications, so i did not make PR for it

**Comment by poissoncorp** [comment]
Hello @danielwinkler 
Thank you for creating this issue 😃 
I've created PR and we're going to release these changes 

_Important note_
Currently, we're working on a v5.2 client with a totally revamped API.
We'll no longer support the v5.0 when it'll be ready.
The v5.2 client is in the beta phase, available here  https://pypi.org/project/ravendb/5.2.0b1 ✌️

**Comment by danielwinkler** [comment]
Hi @poissoncorp 

Thanks a lot for the quick fix!
We will be adapting to the new lib ASAP as it's ready, i just wasn't sure about the stability so i went for the old one.

Keep up the good work!
Cheers,
Daniel
