### ISSUE TITLE
Binding attribute to query

### ISSUE THREAD

**Issue by tronving** [ravendb/RavenDB-Python-Client#138]
I'm trying to create a program that will fetch a value from the database, (which I can manage) but I'm struggling to include the original data in it's response. Because I'll be scanning a large database for thousands of values, I'm using the where_in function to grab them in bulk. The problem is that I need the search value bound to its response. For example, if I search for A, B, and C in the database, I need to grab not just the values of A, B, and C, but also which character (A, B, or C) they're correlated with. At first, I tried to create a list of tuples, with the first element being the character, and the second element filled in by it's response. The issue with that attempt was that there's not always a response of the query value (Say, B was empty), in which case I would be left with 2 responses and 3 characters to assign them to. I'm sorry if this has been a little confusing to read, but this was the best way I could phrase it.

**Comment by ayende** [comment]
Please show the complete code / query that you are using.

In general, you have something like:

```
query = session.query("Items").where_in(hash=hashes_list)
for item in query:
    hash_for_item = item.hash
   #do other stuff
```

**Comment by tronving** [comment]
> Please show the complete code / query that you are using.
> 
> In general, you have something like:
> 
> ```
> query = session.query("Items").where_in(hash=hashes_list)
> for item in query:
>     hash_for_item = item.hash
>    #do other stuff
> ```


Here is my code.
```
class Person:
    def __init__(self,name,age)
        self.name = name
        self.age = age
        self.email = None

A = Person("Joe", 45)
B = Person("Tom", 32)
C = Person("Bob", 70)

people = [A.name, B.name, C.name]

query = session.query("Users").where_in(name=people) # grabs email from username

for email in query:
    # Assign the users email to this value, if it exists
    # How can I link the email to my original query item? Some emails do not exist, so I can't just iterate over the responses and assign them to people.


```

Apologies if there's poor formatting, I'm on mobile.

**Comment by ayende** [comment]
You do it like this:

```
people = [A.name, B.name, C.name]
dic = {}
for person in people:
	dic[person.name] = person

query = session.query("Users").where_in(name=people) # grabs email from username

for user in query:
    dic[user.name].email = user.email
```

So you can do the lookup in memory between the value you searched for and the source.

**Comment by tronving** [comment]
> You do it like this:
> 
> ```
> people = [A.name, B.name, C.name]
> dic = {}
> for person in people:
> 	dic[person.name] = person
> 
> query = session.query("Users").where_in(name=people) # grabs email from username
> 
> for user in query:
>     dic[user.name].email = user.email
> ```
> 
> So you can do the lookup in memory between the value you searched for and the source.

Right, this isn't my issue. The issue is that not every user has an email. If 1 user doesn't have an email, it messes up every other user's email. Just as a reminder, I'm searching through too many lines to just make a database query for each person.

**Comment by ayende** [comment]
What do you mean, a user doesn't have an email? So they won't be in the `query` results, and won't be set.

**Comment by tronving** [comment]
> What do you mean, a user doesn't have an email? So they won't be in the `query` results, and won't be set.

If the user doesn't have an email, they won't be in the database. An input list of `["joe", "tom", "bob"]` would produce an output query with the results `["joe09byers@hotmail.com", "bobsinger14@gmail.com"]`. How could I bind these emails to their proper user?

**Comment by ayende** [comment]
Let's look at that:

```
people = ["joe", "tom", "bob"]
dic={}
for person in people:
    dic[person] = None

query = session.query("Users").where_in(name=people) # grabs email from username
# [Person("joe", "joe09byers@hotmail.com"), Person("bob","bobsinger14@gmail.com")]
for user in query:
    dic[user.name] = user.email

# dic now has:
#dic = { "joe": "joe09byers@hotmail.com", "tom": None, "bob": "bobsinger14@gmail.com"}
```

**Comment by tronving** [comment]
Thanks for the help! I'll try this. Just so you know, there's a pretty big error in the README of this github page. The pip installation for this package is "pyravendb", not "ravendb", which is this guys project: https://github.com/firegrass/ravendb-py.

edit: With your exact code, I'm getting this error:
```Traceback (most recent call last):
  File "c:\Users\trovi\codig\PYTHONSUS\temp\ravenSUS\SauceRaven.py", line 14, in <module>
    query = session.query("Users").where_in(name=people) # grabs email from username
  File "C:\Users\trovi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyravendb\store\session_query.py", line 72, in __call__
    self.index_name, self.collection_name = self._process_query_parameters(index_name, collection_name)
  File "C:\Users\trovi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyravendb\store\session_query.py", line 116, in _process_query_parameters
    collection_name = self.session.conventions.default_transform_plural(self.object_type.__name__)
AttributeError: 'str' object has no attribute '__name__'. Did you mean: '__ne__'?```

**Comment by ppekrol** [comment]
This is correct. We are in a process of development of a new client API under 'ravendb' which at the moment is in 'beta' (https://pypi.org/project/ravendb/5.2.0b1/). To install it you need to execute `pip install ravendb==5.2.0b1`. Previous client is available under 'pyravendb'.

**Comment by tronving** [comment]
Alright, but if you just do the command `pip install ravendb`, it will install an ancient and probably bug-filled implementation of pyravendb, so you should probably change the readme to clarify that. Either way, could you help me fix the error I mentioned in my previous comment?

**Comment by poissoncorp** [comment]
Hi @tronving,
I see that you could have used **pyravendb** client while executing the code.
`File "C:\Users\trovi\AppData\Local\Programs\Python\Python310\lib\site-packages\pyravendb\store\session_query.py"`

Currently, as @ppekrol mentioned, we're developing a modern database client, the next version of  `ravendb` package.
The old package `pyravendb` is almost deprecated.
To solve the problem above, I'd suggest using `ravendb` beta.

`pip install ravendb==5.2.0b1`

If the installation of a new client beta isn't possible here, please let me know - but if any problems occur during the work with `ravendb` they'll be much easier to solve.

I'll be here to help you, please let me know what you think 🙂
