### ISSUE TITLE
Multiple queries in one session return crippled instances

### ISSUE THREAD

**Issue by AxelZschutschke** [ravendb/RavenDB-Python-Client#154]
It seems multiple queries containing the same result data return only a shallow instance for previously fetched results (cannot fetch metadata). Following scenario:

res1 = list(session.query(object_type=mytype, collection_name="mycollection"))
res2 = list(session.query(object_type=mytype, collection_name="mycollection"))
res3 = session.load("mycollection/1-A")

res1[0].Id -> returns correct Id
res2[0].Id -> returns correct Id
res3.Id -> returns correct Id

session.advanced.get_metadata_for(res1[0]) -> returns correct info
session.advanced.get_metadata_for(res3) -> returns correct info
session.advanced.get_metadata_for(res2[0]) -> returns below error

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyravendb/store/document_session.py", line 99, in __getitem__
    return self._hashable_items[key]
KeyError: <vrp.database.Generic object at 0x7fe7c79e6620>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/pyravendb/store/document_session.py", line 621, in get_metadata_for
    return self.session.documents_by_entity[entity]['metadata']
  File "/usr/local/lib/python3.10/site-packages/pyravendb/store/document_session.py", line 101, in __getitem__
    return self._unhashable_items[key]
  File "/usr/local/lib/python3.10/site-packages/pyravendb/store/document_session.py", line 61, in __getitem__
    return self.unhashable_items[_RefEq(key)]
KeyError: <pyravendb.store.document_session._RefEq object at 0x7fe7c8497910>

**Comment by poissoncorp** [comment]
Hi @AxelZschutschke thank you for creating this issue 😊.
I see that you could be using the **pyravendb** client while executing the code.

Currently, we're developing a modern database client, the next version of the `ravendb` package - there'll be a release very soon.
The old package `pyravendb` is almost deprecated.

The error shouldn't be relevant on the v5.2b version - we've made a few fixes regarding metadata and caching. 
I'd suggest using **ravendb** beta.

It's available via
`pip install ravendb==5.2.0b2`
or
`pip install --upgrade ravendb==5.2.0b2`

The v5.2b query:
`session.query_collection("mycollection", mytype)`

Please let me know if that fixes the problem.

I'll be here to help you, please let me know what you think 🙂

**Comment by AxelZschutschke** [comment]
Yes, this fixes the problem -- I'll close the issue again ;)

**Comment by AxelZschutschke** [comment]
Thank you
