### ISSUE TITLE
"select_fields" ignores "where_equals" results

### ISSUE THREAD

**Issue by canaldkz** [ravendb/RavenDB-Python-Client#157]
``` python
def get_manga(self, manga_id: str):
        with self.open_session() as session:
            response = list(
                session.advanced.document_query(collection_name="Mangas")
                .where_equals("Id", manga_id)
                .select_fields(MangaResult, *[f.name for f in fields(MangaResult)])
            )
        return response if len(response) else None
```
Returned response list contains all documents in collection with selected fields.
But if remove `.select_fields`, it returns one document with all fields. Should I filter out required fields on python side?
ravendb = "5.2.0b2"

**Comment by poissoncorp** [comment]
Hi @canaldkz,
Thank you for creating this issue.
Generally, using `where_equals` on the document id field is greatly unadvised.
It's advised to use the `session.load` method for the purpose of loading a single document with a specific `Id`.
Although if your use case forces a such way to load the document, you may type "id()" as a field key in `where_equals` but it leads to the performance loss.

Please, let me know if that solves the problem.

**Comment by ayende** [comment]
@poissoncorp Actually a query such as `where id() = $id` is turned into a `load` operation on the server and it optimized.
That allows you to then apply select / projection on this.

**Comment by ayende** [comment]
Also, the issue appears to be related to _not_ filtering when we have `select_fields`, no?

**Comment by poissoncorp** [comment]
@ayende Yes, you're right - and after some tests, I've noticed a big difference between the queries sent to the server that isn't related to just only `select_fields`.  The `where` part is missing, and currently, I'm figuring out why. 
@canaldkz I'll update here

**Comment by poissoncorp** [comment]
@canaldkz 
I've found a bug inside the query-building process.
I've fixed it, we'll release a patched version as soon as possible.
You can take a look at the linked PR. #159 

After the release, using the `select_fields` will work correctly with `where_equals("id()", your_key)`!
If that solves the problem, please close this issue.
Otherwise, please let us know :]
