### ISSUE TITLE
log_query quite chatty on INFO level, in v5.2.1

### ISSUE THREAD

**Issue by hanssens** [ravendb/RavenDB-Python-Client#167]
In the recent v5.2.1 release, the logging is quite chatty on INFO level. For your consideration, would it be possible to [configure the QueryOperation](https://github.com/ravendb/ravendb-python-client/blob/6866b78596d1d85a80134ddae6aa3429c894ae24/ravendb/documents/session/operations/query.py#L77) to use the DEBUG level by default, instead of INFO?

(Great job on the new release, btw)

**Comment by poissoncorp** [comment]
Hello, @hanssens. Thank you for bringing this inconvenience to our attention!
I'll prepare a patch and include it in the upcoming release.
I've opened an issue on our bugtracker, you can track the status of the ticket [here](https://issues.hibernatingrhinos.com/issue/RDBC-677/Configure-the-QueryOperation-to-use-the-logging-on-the-DEBUG-level-by-default-instead-of-INFO)
Thank you once again! 😄
