### ISSUE TITLE
load method does not return nested objects

### ISSUE THREAD

**Issue by nazzour** [ravendb/RavenDB-Python-Client#178]
I stored the following object in my db:
_"""
{
    "Id": "meics/c201a1b5-e606-4e3f-ba5b-f77e0c5e8432",
    "Status": "Active",
    "Channel": "string",
    "Unity": "string",
    "Creation": "2023-04-14T07:50:43.3445080",
    "Last_Update": "2023-04-14T07:50:43.3445080",
    "RemoteErrors": [
        {
            "TransactionId": "c201a1b5-e606-4e3f-ba5b-f77e0c5e8432",
            "ErrorId": "14c92abb-9d4c-434b-83ce-0f05e0724c8d",
            "RemoteErrorType": "Send Request to Remote",
            "RemoteErrorClass": "str(e.__class__)",
            "InternalErrorCode": 500,
            "RemoteErrorDetails": "repr(e.__cause__)",
            "RemoteErrorAddDateTime": "2023-04-14T07:50:47.1114320"
        }
    ],
    "@metadata": {
        "@collection": "MeiModels",
        "Raven-Python-Type": "dbmodels.meimodel.MeiModel"
    }
}
""_

when I load the document using the session load method I get an empty "RemoteErrors" array. Any help please ?

**Comment by poissoncorp** [comment]
Hi @nazzour,
It looks strange, could you provide us a chunk of your code, where the `session.load` is executed? 
It'd let us investigate the root problem of your issue faster, and provide more precise advice :]

**Comment by nazzour** [comment]
Of course, it is a very simple code :
`def get_transaction(tcn: str, db: ravendb.DocumentSession = Depends(get_db)):`
    ` logger.info("Fetching transaction with Id {0}", repr(tcn));`
    ` response = db.load('meics/' + tcn);`
   ` logger.info("Fetching meics with Id {0}", repr(response.Id));`
   ` logger.info("Fetching meics with Errors {0}", repr(response.RemoteErrors));`

The last line prints an empty array

**Comment by poissoncorp** [comment]
The `load` method takes up to 3 arguments, and only the first (the `key_or_keys`) is required.
The second argument is an `object_type`. It's the type of expected result. However, it's optional - the type is usually saved to the metadata, and it's fetched from there while loading. If it cannot be imported, the result is represented as a `dict`. 

I believe that the server sends the correct JSON of your object in the payload, so the problem is very likely to be related to deserializing and initializing your object.

For assurance, replace your load line with the line below, until we find the error cause:
`response = db.load('meics/' + tcn, dbmodels.meimodel.MeiModel)`
We'll be 100% sure that the `MeiModel.__init__()` will be used to initialize the object from the JSON.

It is possible for you to paste here the `MeiModel` class definition?
We need to take a look at the `MeiModel.__init__()`

**Comment by poissoncorp** [comment]
**Note:**
We have a feature that allows defining custom JSON deserialization for your classes. It's helpful if your type has nested objects, that you want also to be deserialized, or some other unusual behavior.

Defining `to_json` and `from_json` methods is a way to handle the serialization process manually, the `ravendb` module will use these methods while loading/writing to the database.

For example, the `from_json` method that handles datetime string in an unusual format, coming from the server:

```py
class Order:
    def __init__(self, Id: str, ordered_at: datetime.date):
        self.Id = Id
        self.ordered_at = ordered_at
 
    @classmethod
    def from_json(cls, json_dict: Dict) -> Order:
        return cls(
            json_dict.get("Id", None),
            Utils.string_to_datetime(json_dict.get("ordered_at", None)),
        )
 
    # Writing custom deserializers is simple, just create static/class method from_json
    # that takes dictionary as an argument and returns the object you desire
 
    # The same thing about serializers - create to_json method that returns dict (your json object representation)
```


It can be also helpful while **_debugging_** - `from_json` takes an incoming JSON `dict` representation as an argument. It lets to look up what's coming from the server.

**Comment by nazzour** [comment]
Thank you for the quick reply. This is my class 
```
import datetime
from typing import List

class ErrorModel:
    def __init__(self, TransactionId: str=None, ErrorId: str=None,  RemoteErrorClass: str=None,
                 InternalErrorCode: str=None,
                 RemoteErrorDetails: str=None, RemoteErrorAddDateTime: datetime.datetime=None):
        self.TransactionId =  TransactionId
        self.ErrorId = ErrorId
        self.RemoteErrorClass = RemoteErrorClass
        self.InternalErrorCode = InternalErrorCode
        self.RemoteErrorDetails = RemoteErrorDetails
        self.RemoteErrorAddDateTime = RemoteErrorAddDateTime

class MeiModel:
    def __init__(self, Id: str = None, status: str=None, channel: str=None, unity: str=None, creation: datetime.datetime = None,
                 last_update: datetime.datetime = None, errors: List[ErrorModel]=[]):
        self.Id = Id
        self.Status = status
        self.Channel = channel
        self.Unity = unity
        self.Creation = creation
        self.Last_Update = last_update
        self.RemoteErrors = errors
```
Any advice please ?

**Comment by poissoncorp** [comment]
Let me know if adding `from_json` to your class definition helps. Here's the code:
```
class MeiModel:
    def __init__(
        self,
        Id: str = None,
        status: str = None,
        channel: str = None,
        unity: str = None,
        creation: datetime.datetime = None,
        last_update: datetime.datetime = None,
        errors: List[ErrorModel] = [],
    ):
        self.Id = Id
        self.Status = status
        self.Channel = channel
        self.Unity = unity
        self.Creation = creation
        self.Last_Update = last_update
        self.RemoteErrors = errors

    @classmethod
    def from_json(cls, json_dict: Dict) -> "MeiModel":
        return cls(
            json_dict["Id"],
            json_dict["Status"],
            json_dict["Channel"],
            json_dict["Unity"],
            json_dict["Creation"],
            json_dict["Last_Update"],
            json_dict["RemoteErrors"],
        )
```
If it doesn't, please place a breakpoint on the first `from_json` line, and let us know if the `json_dict` contains correct data.

**Comment by nazzour** [comment]
Thank you it works now. I have a quick question about the python client, when I add a document with an existing I don't receive any error. This happens only if the document is already in memory. What is the best way to avoid this behavior ? Should I check each time if the document exists before inserting ? Thank you

**Comment by poissoncorp** [comment]
Storing a document with the same id as the other document, already stored before in the same session, _doesn't_ result in an exception. (Correct me please, if I didn't understand you correctly).

If you don't want to perform some action, when the document has been already stored, you can use `session.advanced.is_loaded` method. With the fact in mind, that the changes you've made will be written on the `session.save_changes()`, we can prevent overwriting the changes before the `save_changes`, by calling the method that I've mentioned. Let me know if that works for you :)

**Comment by poissoncorp** [comment]
Storing a document with the same id as the other document, already stored before in the same session, _doesn't_ result in an exception. (Correct me please, if I didn't understand you correctly).

It is true. However, calling the `save_changes()` with such data loaded into the session will result in NonUniqueObjectException.

```py
ravendb.exceptions.exceptions.NonUniqueObjectException: Attempted to associate a different object with id {your id}.
```

If you don't want to perform some action, when some document has been already stored in the session, you can use `session.advanced.is_loaded` method. 

---

If you don't want to **update** your document, that's already in the database (you're focused only on creating the documents), you may try to load the document to see if the result is `None`. If so, you'll be sure that the document doesn't exist remotely. After all, you need to communicate with your remote server to make such assurance.

**Comment by poissoncorp** [comment]
Let me know if that works for you, @nazzour :]

**Comment by nazzour** [comment]
Sorry, I think that I did not explain well. I am creating a document with the same Id in another session. To prevent this behavior I have to check first if the document has been already stored right ? So each time I want to create a document I have to try to load an existing one using the Id. Am I correct ? My aim it to prevent to create/change an existing document and throw an exception if the user tries to create a new document with an existing Id.

**Comment by ml054** [comment]
@nazzour Many depends on your use case. 

If you have high amount of concurrent writes to same document, I think it might be better to use patch api. Since then you send to server things like: Add 1 to field votesCount. Push element Python to array in field: favLangs, etc. 
More info is here: https://ravendb.net/docs/article-page/5.4/csharp/client-api/operations/patching/single-document

If you don't modify same document too often then session is great. As you can load/modify/save w/o any worries. 

Another interesting subject is optimistic concurrency described here: https://ravendb.net/docs/article-page/5.4/csharp/client-api/session/configuration/how-to-enable-optimistic-concurrency 

If most of saves are related to bumping values, you might also use counters, or if you play with time then timeseries will be right for you. 

In case of futher questions, please describe in more details your use case, as usually solution depends on use case. :)

**Comment by nazzour** [comment]
Thank you for your help and quick replies.

**Comment by ml054** [comment]
You are welcome. Happy coding with RavenDB. :)
