### ISSUE TITLE
Unable to create documents with server generated UUID's

### ISSUE THREAD

**Issue by paul-old** [ravendb/RavenDB-Python-Client#198]
We want to store documents and let RavenDB assign Guid identifiers to the documents. From the [documentation](https://ravendb.net/docs/article-page/6.0/csharp/client-api/document-identifiers/working-with-document-identifiers):

_Then, you have to provide the string.Empty as the value of the Id property_

We have tried setting the `Id = ""` but receive the error below when saving changes. However, the document is correctly stored in the database with id() = guid and Id = "".
Setting `Id = None` the document stores without an error but the id() and Id are set to the form: products/1-A.

Traceback:
File "raven_crud.py", line 77, in store_registration
    session.save_changes()
  File "ravendb/documents/session/document_session.py", line 134, in save_changes
    save_changes_operation.set_result(command.result)
  File "ravendb/documents/operations/batch.py", line 72, in set_result
    self.__on_successful_request.clear_session_state_after_successful_save_changes()
  File "ravendb/documents/session/document_session_operations/in_memory_document_session_operations.py", line 1825, in clear_session_state_after_successful_save_changes
    self.__session._documents_by_id.pop(key)
  File "ravendb/tools/utils.py", line 192, in pop
    return super(CaseInsensitiveDict, self).pop(self.__class__._lower_if_str(key), *args, **kwargs)
KeyError: ''

**Comment by poissoncorp** [comment]
Hello @PaulKlaas,
Thank you for opening this issue. The behavior seemed odd, and after a brief investigation, I discovered a bug. 
I've pushed the fix and linked the pull request to this issue. The pull request contains the test confirming that the behavior you described works as it should from now on.

We'll release the fix in the upcoming version of the client, which will also include time series API. 
The release is coming very soon, we're posting every release info on our [project releases](https://github.com/ravendb/ravendb-python-client/releases)  page in this repo.

If you have any other questions regarding this issue, I'm here to help :)

**Comment by poissoncorp** [comment]
Hello @PaulKlaas,
Thank you for opening this issue. The behavior seemed odd, and after a brief investigation, I discovered a bug.
I've pushed the fix and linked the pull request to this issue. The pull request contains the test confirming that the behavior you described works as it should from now on.

We'll release the fix in the upcoming version of the client, which will also include time series API.
The release is coming very soon, we're posting every release info on our [project releases](https://github.com/ravendb/ravendb-python-client/releases) page in this repo.

If you have any other questions regarding this issue, I'm here to help :)
Thanks

**Comment by klaassens** [comment]
@ml054 Thanks for the fix, it is a step in the right direction but unfortunately still ends up with a botched document.

By setting Id = "" we end up with a document with @id as the generated UUID but Id in the document itself is assigned to "". Is there any way to either set Id to the generated UUID or don't include it in the document at all?
Currently:
```
 {
            "Id": "",
            "title": "iPhone Y",
            "manufacturer": "Apple",
            "@metadata": {
                "@collection": "Products",
                "Raven-Python-Type": "__main__.Product",
                "@change-vector": "C:1027705-63CKfhE1G02uaoUbVT6Hxg, B:1019472-D+grPhn0LEWxgkzi2Eq3pA, A:1024197-z513QARBcU+VJM+Oc0Jrdw",
                "@flags": "FromReplication",
                "@id": "44e0d566-e783-4eae-b72c-fd4bc6da0035",
                "@last-modified": "2024-02-29T14:23:28.9212273Z",
            }
```

**Comment by ayende** [comment]
We won't modify the document `Id` on save, I think. What happens when you re-load the document?

**Comment by klaassens** [comment]
Loading by the Id actually works and Product.Id returns the generated UUID. 
However, the Id remains "" in ravendb studio.

We also load raven documents which are stored from .NET, to access their Id in python we use:
`getattr(document, "@metadata")["@id"]`

This does not work for the documents stored from Python:
_Product' object has no attribute '@metadata'_

The endgoal is to handle documents the same way regardless if they are stored from Python or .NET.
