### ISSUE TITLE
Letting RavenDB assign GUID's ends up with an empty string as the Id saved in the document

### ISSUE THREAD

**Issue by klaassens** [ravendb/RavenDB-Python-Client#209]
We want to store documents and let RavenDB assign Guid identifiers to the documents. From the [documentation](https://ravendb.net/docs/article-page/6.0/csharp/client-api/document-identifiers/working-with-document-identifiers):

Then, you have to provide the string.Empty as the value of the Id property.

By setting Id = "" we end up with a document with @id as the generated UUID but Id in the document itself is assigned to "", for example:
```
 {
            "Id": "",
            "title": "iPhone Y",
            "manufacturer": "Apple",
            "@metadata": {
                "@collection": "Products",
                "Raven-Python-Type": "__main__.Product",
                "@change-vector": "C:1027705-63CKfhE1G02uaoUbVT6Hxg, B:1019472-D+grPhn0LEWxgkzi2Eq3pA, A:1024197-z513QARBcU+VJM+Oc0Jrdw",
                "@flags": "FromReplication",
                "@id": "44e0d566-e783-4eae-b72c-fd4bc6da0035",
                "@last-modified": "2024-02-29T14:23:28.9212273Z",
            }
```

Relates to this [issue.](https://github.com/ravendb/ravendb-python-client/issues/198)

**Comment by poissoncorp** [comment]
Hello, @klaassens 
Thank you for opening this issue
I'll dive into it soon, I'll keep you posted here on the progress made

**Comment by poissoncorp** [comment]
I've dived into the issue, and I see, that the behavior you're explaining is correct, so I may not accurately understand the issue. Let me explain:
1. When assigning an empty string to a document's identity field in RavenDB, you're essentially telling the database to generate a UUID as the identifier for that document. 

2. After invoking the `save_changes()` method in the Python client, the client retrieves the response from the server. This response includes the newly generated UUID, making it readily accessible in various ways. You can retrieve it by accessing the corresponding field value (`product.Id`), examining the metadata's `@id` property (`session.advanced.get_metadata_for(product)["@id"]`), or by using `session.advanced.get_document_id(product)` (.NET client example). This accessibility ensures that you can immediately utilize the newly created ID for further operations.

3. The document having an empty "Id" field on the server side signifies that it was created with an automatically generated UUID as its unique identifier.

4. When viewing the document in RavenDB Studio's user interface, you'll notice that the document ID is displayed correctly across all views. This indicates that the UUID generated server-side is effectively propagated and utilized throughout the database environment.

I'm attaching a test that I've run to verify the behavior
```py
 def test_create_document_with_server_generated_guid(self):
        guid_from_server = None
        with self.store.open_session() as session:
            product = Product("Test")
            session.store(product)
            session.save_changes()
            guid_from_server = product.Id

        with self.store.open_session() as session:
            product = session.load(guid_from_server)
            metadata_id = session.advanced.get_metadata_for(product)["@id"]
            identity = session.advanced.get_document_id(product)
            id_prop = product.Id

            self.assertEqual(id_prop, identity)
            self.assertEqual(id_prop, metadata_id)
            self.assertEqual(id_prop, guid_from_server)

        with self.store.open_session() as session:
            product = session.load(guid_from_server)
            product.Id = ""
            session.save_changes()

        with self.store.open_session() as session:
            product = session.load(guid_from_server)
            metadata_id1 = session.advanced.get_metadata_for(product)["@id"]
            identity1 = session.advanced.get_document_id(product)
            id_prop1 = product.Id

            self.assertEqual(id_prop, id_prop1)
            self.assertEqual(id_prop, metadata_id1)
            self.assertEqual(id_prop, identity1)
```

**Comment by ayende** [comment]
The problem is that the _document_ has a property named `Id` that is set to an empty string.
In C#, the `Id` property is removed entirely

**Comment by poissoncorp** [comment]
Hi,
I've recognized that its indeed an issue, server documents shouldn't have the 'Id' field.
I prepared a fix in this PR:
https://github.com/ravendb/ravendb-python-client/pull/211
