### ISSUE TITLE
How do connect to ravendb via SSL

### ISSUE THREAD

**Issue by MohMehrnia** [ravendb/RavenDB-Python-Client#58]
How do connect to ravendb via connect with below code:
`store = document_store.DocumentStore(urls=["https://localhost:4343"], database="SeSimi")`

**Comment by IdanHaim** [comment]
You will need to have a certificate and add the path to it when you open a documentstore
`store = document_store.DocumentStore(urls=["https://localhost:4343"], database="SeSimi", certificate=path_to_PEM_file)`. 
You can create a certificate from the setup wizard when you open a new server or if you have one of your own.

**Comment by MohMehrnia** [comment]
When i set crtificate, show me below eeor:
OpenSSL.crypto.Error: [('asn1 encoding routines', 'asn1_d2i_read_bio', 'not enough data')]
