### ISSUE TITLE
Please, add support for *.pfx certificates

### ISSUE THREAD

**Issue by jpazsedano** [ravendb/RavenDB-Python-Client#69]
There are no docs about how to use authentication with the Python client, but looks like it only supports *.pem certificates.

This is a big deal because a *.pfx certificate converted into *.pem doesn't work either. If I separate certificate and private key, whatever I load it says that the other is missing. If I put everything into the same *.pem file, it just says that the certificate is wrong.

So if your server is protected with a *.pfx certificate, you just can't use the python client.

**Comment by w0pr** [comment]
It should work (at least it does for me) if you combine key & cert in the .pem file like this:

> -----BEGIN RSA PRIVATE KEY----- 
> (Your Private Key) 
> -----END RSA PRIVATE KEY----- 
> -----BEGIN CERTIFICATE----- 
> (Your Certificate) 
> -----END CERTIFICATE----- 

I'm still having issues with using the changes API, but I suspect this is a websocket-client thing...

**Comment by ayende** [comment]
@jpazsedano The `pfx` isn't supported by the Python `requests` module. Either `pem` or `cer` / `key` should work.

**Comment by ayende** [comment]
For future reference, you can also use:

https://gist.github.com/erikbern/756b1d8df2d1487497d29b90e81f8068
